[http.middlewares]
  [http.middlewares.redirect-https.headers]
    sslRedirect = true
  [http.middlewares.cors.headers]
    accessControlAllowMethods = "GET,OPTIONS,PUT"
    accessControlAllowOriginListRegex = ".*"
    accessControlAllowHeaders = ["content-type", "x-auth-userinfo"]
    accessControlMaxAge = 100
    addVaryHeader = true

  [http.middlewares.no-cache.headers]
   [http.middlewares.no-cache.headers.CustomResponseHeaders]
      Cache-Control = "no-cache"
      Pragma = "no-cache"